enabled_locales: ["en", "vn"]
client:
  host: "localhost:3000"
src:
  logo: "Logo.png"
  assets_path: "app/assets/images/"
validation:
  name:
    length:
      max: 50
  email:
    length:
      max: 50
    valid_regex: !ruby/regexp /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
    pwd_reset_expired_hours: 2
  password:
    length:
      min: 6
  phone:
    length: 10
  description:
    length:
      max: 200
  rating:
    min: 0
    max: 5
  image:
    max_size: 5
    type: ["image/jpeg", "image/gif", "image/png"]
    type_accepted: "image/jpeg,image/gif,image/png"
  item:
    min: 0
avatar:
  size:
    profile: 80
    list: 50
    follower: 30
user:
  admin:
    name: "Tran Anh Tuan"
    email: "tatuan19@gmail.com"
    password: "123456"
  faker:
    password: "password"
room_types:
  max_in_rows: 4
  image_size: "500x500"
seed:
  lorem: "Lorem Ipsum is simply dummy text of the printing and typesetting industry."
  room_types:
    max: 4
    name: [
      "Single bed room (SGL)",
      "Twin bed room (TWN)",
      "Double bed room (DBL)",
      "Triple bed room (TRPL)"
    ]
    description: [
      "Phòng có một giường đơn, dành cho 1 người ở.",
      "Phòng nghỉ có hai giường ngủ, dành cho hai người.",
      "Là loại phòng dành cho các cặp đôi, có 1 giường kích thước lớn.",
      "Phòng ngủ lớn dành cho 3 người, có thể là loại 3 giường đơn
      hoặc 1 chiếc giường lớn và 1 giường nhỏ."
    ]
    image: [
      "room1.jpg",
      "room2.jpg",
      "room3.jpg",
      "room4.jpg"
    ]
not_found_page: "public/404.html"
format_date_time: "%Y-%m-%d %I:%M %p"
default_ava:
  male: "male.jpg"
  female: "female.jpg"
due_time: 720
